on:
  push:
    branches:
      - master
      - test

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Package
      run: |
        make setup clean
        make
    - name: Commit
      run: |
        env
